// 动态工具模块：由 ToolManifest（evolution/tool_ext.rs）在 add_tool 时重新生成。
// Dynamic tools module: regenerated by ToolManifest (evolution/tool_ext.rs) at add_tool time.
// 初始版本为空；每次 /add-tool 后 regenerate_mod_rs 会覆写本文件，
// The initial version is empty; regenerate_mod_rs overwrites this file after each /add-tool,
// 声明新的 pub mod 并在 load_all() 中注册。下次 cargo build 即编译进项目。
// declaring new pub mod entries and registering them in load_all(). The next cargo build compiles them in.
use rig_agent::tool::ToolSet;

/// 返回所有动态工具。工具为空时返回空 ToolSet。
/// Returns all dynamic tools. Returns an empty ToolSet when there are no tools.
/// 本函数在编译期确定工具列表——add_tool 生成的新工具需要重新 cargo build 才生效。
/// The tool list is fixed at compile time — a tool generated by add_tool takes effect only after a fresh cargo build.
// TODO: 待接入 add_builtin_tools() 后启用（rig 0.41 builder API 适配）。
#[allow(dead_code)]
pub fn load_all() -> ToolSet {
    ToolSet::default()
}
